### ISSUE TITLE
Zero width whitespace in a filename MetricKit.md

### ISSUE THREAD

**Issue by kosta-khetagurov** [jVirus/ios-learning-materials#17]
Hi!
I accidentally found out that the link supposed to lead to MetricKit.md in README.md leads to 404 page. The problem is because of whitespace in the filename MetricKit.md. I suggest to clean filename from it, it will make the link more readable.

**Comment by jVirus** [comment]
Hi, 

You are welcome to propose a pull request with a fix. That way the changes will be propagated much faster.

Thank you for the feedback.

**Comment by jVirus** [comment]
The issue has been fixed in 5eaa9b4b3e6eb138394c3bf2fdb244b358b38e58. Thank you!
