### ISSUE TITLE
Link Problem

### ISSUE THREAD

**Issue by AlirezaSN** [jVirus/ios-learning-materials#18]
Howdy, the link of [Pick your poison](https://ruiper.es/2019/10/12/pick-your-poison/) (in Business section) returns 404 error.

Thanks 👋

**Comment by AlirezaSN** [comment]
also [iOS Development Team in 2019](https://exyte.com/blog/ios-development-team-in-2019)

**Comment by jVirus** [comment]
Hi @AlirezaSN,

It seems like the `Pick your poison` article is no longer available for free and the `iOS Development Team in 2019` article isn't available at all. 

Thank you very much for pointing that out! ;) The broken links will be removed

**Comment by AlirezaSN** [comment]
i write a python script that extracts broken links. i attached the output file in this commit.
best of luck 👋

[output.txt](https://github.com/jVirus/ios-learning-materials/files/4859597/output.txt)
