### ISSUE TITLE
Question about Contributing.md

### ISSUE THREAD

**Issue by philipturner** [jVirus/ios-learning-materials#63]
I would like to add [ARHeadsetKit](https://github.com/philipturner/ARHeadsetKit) as both a "tool" and a learning course (look at its "Tutorial Series" on the README). It was published after you created the ARKit section, so it has yet to be included.

For more reference information on this framework, check out [my article](https://philipturner.github.io/first-affordable-ar-headset).

Your Contributing.md and pull request history don't seem like they are welcome to outside contributors adding individual frameworks/courses. To save time, I won't make a PR until I know it has a chance of being accepted.

Are you open to adding ARHeadsetKit to this repository?

**Comment by philipturner** [comment]
My app [AR MultiPendulum](https://github.com/philipturner/ar-multipendulum) could also go under the "code" section in ARKit.md.

**Comment by philipturner** [comment]
Also, consider adding [DL4S](https://github.com/palle-k/DL4S) under "tools" in MachineLearning.md.

**Comment by jVirus** [comment]
My apologies for a late reply @philipturner. I took a look at your projects and articles, great work! For sure you'r more than welcome to add them without via a pool request

**Comment by jVirus** [comment]
The issue has been resolved with #64
